services:
    board-room:
        image: board-room:0.3
        build:
            context: board-room
            network: host
        ports:
            - "8080:8080"
        depends_on:
            - board-postgres
            - board-redis
        environment:
            board.ssl: "false"
            board.postgres.url: "jdbc:postgresql://board-database:5432/board"
            board.postgres.user: "board_room"
            board.postgres.password: "changeme"
            board.redis.url: "board-redis:6379"
    board-frontend:
        image: board-frontend
        build:
            context: board-frontend
        ports:
            - "80:80"
    board-postgres:
        build:
            context: board-postgres
        environment:
            POSTGRES_PASSWORD: "changeme"
        ports:
            - "5432:5432"
    board-redis:
        build:
            context: board-redis
        ports:
        -   "6379:6379"