services:
    board-server:
        image: board-server:0.2
        build:
            context: board-server
        ports:
            - "80:80"
        environment:
            board.ssl: "false"
    database:
        image: postgres
        environment:
            POSTGRES_PASSWORD: changeme
        ports:
            - "5432:5432"