services:
# WebSocket backend
    scribbleshare-room:
        image: scribbleshare-room
        build:
            context: scribbleshare-room
        ports:
            - "8080:80"
        depends_on:
            scribbleshare-postgres:
                condition: service_healthy
            scribbleshare-keydb:
                condition: service_healthy
        environment:
            scribbleshare.ssl: "false"
            scribbleshare.postgres.url: "jdbc:postgresql://scribbleshare-postgres:5432/scribbleshare"
            scribbleshare.postgres.user: "scribbleshare_room"
            scribbleshare.postgres.password: "changeme"
            scribbleshare.redis.url: "redis://default:changeme@scribbleshare-keydb:6379"
# HTTP backend
    scribbleshare-backend:
        image: scribbleshare-backend
        build:
            context: scribbleshare-backend
        depends_on:
            scribbleshare-postgres:
                condition: service_healthy
            scribbleshare-keydb:
                condition: service_healthy
        environment:
            scribbleshare.ssl: "false"
            scribbleshare.postgres.url: "jdbc:postgresql://scribbleshare-postgres:5432/scribbleshare"
            scribbleshare.postgres.user: "scribbleshare_backend"
            scribbleshare.postgres.password: "changeme"
            scribbleshare.redis.url: "redis://default:changeme@scribbleshare-keydb:6379"
# Reverse proxy
    scribbleshare-nginx:
        image: scribbleshare-nginx
        build:
            context: scribbleshare-nginx
        ports:
            - "80:80"
# Database
    scribbleshare-postgres:
        build:
            context: scribbleshare-postgres
        ports:
            - "5432:5432"
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 3s
            timeout: 3s
            retries: 5
        environment:
            POSTGRES_PASSWORD: "changeme"
    scribbleshare-keydb:
        build:
            context: scribbleshare-keydb
        ports:
            - "6379:6379"
        healthcheck:
            test: [ "CMD", "keydb-cli", "ping" ]
            interval: 3s
            timeout: 3s
            retries: 5

#
# Build
#
# Build jars with Gradle for scribbleshare-room and scribbleshare-backend
    scribbleshare-gradle:
        image: scribbleshare-gradle
        build:
            context: .
# Minify/compress HTML/JS/CSS/Assets
    scribbleshare-frontend:
        image: scribbleshare-frontend
        build:
            context: scribbleshare-frontend