services:
# WebSocket backend
    scribbleshare-room:
        image: stzups/scribbleshare-room:0.0
        build:
            context: scribbleshare-room
        ports:
            - "8080:80"
        depends_on:
            scribbleshare-postgres:
                condition: service_healthy
#            scribbleshare-keydb:
#                condition: service_healthy
        environment:
            scribbleshare.ssl: "false"
            scribbleshare.postgres.url: "jdbc:postgresql://scribbleshare-postgres:5432/scribbleshare"
            scribbleshare.postgres.user: "scribbleshare_room"
            scribbleshare.postgres.password: "changeme"
#            scribbleshare.redis.url: "redis://default:changeme@scribbleshare-keydb:6379"
# App backend
    scribbleshare-app:
        image: stzups/scribbleshare-app:0.0
        build:
            context: scribbleshare-app
        depends_on:
            scribbleshare-postgres:
                condition: service_healthy
#            scribbleshare-keydb:
#                condition: service_healthy
        environment:
            scribbleshare.ssl: "false"
            scribbleshare.postgres.url: "jdbc:postgresql://scribbleshare-postgres:5432/scribbleshare"
            scribbleshare.postgres.user: "scribbleshare_backend"
            scribbleshare.postgres.password: "changeme"
#            scribbleshare.redis.url: "redis://default:changeme@scribbleshare-keydb:6379"
# Reverse proxy
    scribbleshare-nginx:
        image: stzups/scribbleshare-nginx:0.0
        build:
            context: scribbleshare-nginx
        depends_on:
            scribbleshare-app:
                condition: service_started
        ports:
            - "80:80"
# Database
    scribbleshare-postgres:
        image: stzups/scribbleshare-postgres:0.0
        build:
            context: scribbleshare-postgres
        ports:
            - "5432:5432"
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 5s
            timeout: 5s
            retries: 5
        environment:
            POSTGRES_PASSWORD: "changeme"
#    scribbleshare-keydb:
#        build:
#            context: scribbleshare-keydb
#        ports:
#            - "6379:6379"
#        healthcheck:
#            test: [ "CMD", "keydb-cli", "ping" ]
#            interval: 5s
#            timeout: 5s
#            retries: 5