services:
# WebSocket backend
    scribbleshare-room:
        image: stzups/scribbleshare-room
        networks:
            - scribbleshare-network
            - scribbleshare-external-network
        build:
            context: scribbleshare-room
        ports:
            - "52853:52853"
        depends_on:
            scribbleshare-postgres:
                condition: service_healthy
#            scribbleshare-keydb:
#                condition: service_healthy
#        healthcheck:
#            test: [ "CMD", "curl -sf http://localhost:52853/healthcheck || exit 1" ]
#            interval: 5s
#            timeout: 5s
#            retries: 5
        environment:
            scribbleshare.ssl: "false"
            scribbleshare.port: "52853"
            scribbleshare.postgres.url: "jdbc:postgresql://scribbleshare-postgres:5432/scribbleshare"
            scribbleshare.postgres.user: "scribbleshare_room"
            scribbleshare.postgres.password: "changeme"
            scribbleshare.domain: "scribbleshare.com"
#            scribbleshare.redis.url: "redis://default:changeme@scribbleshare-keydb:6379"
# App backend
    scribbleshare-app:
        image: stzups/scribbleshare-app
        networks:
            - scribbleshare-network
        ports:
        - "80:80"
        build:
            context: scribbleshare-app
        depends_on:
            scribbleshare-postgres:
                condition: service_healthy
#            scribbleshare-keydb:
#                condition: service_healthy
#        healthcheck:
#            test: [ "CMD", "curl -sf http://localhost:80/ || exit 1" ]
#            interval: 5s
#            timeout: 5s
#            retries: 5
        environment:
            scribbleshare.ssl: "false"
            scribbleshare.postgres.url: "jdbc:postgresql://scribbleshare-postgres:5432/scribbleshare"
            scribbleshare.postgres.user: "scribbleshare_backend"
            scribbleshare.postgres.password: "changeme"
            scribbleshare.domain: "scribbleshare.com"
#            scribbleshare.redis.url: "redis://default:changeme@scribbleshare-keydb:6379"
# Reverse proxy
#    scribbleshare-nginx:
#        image: stzups/scribbleshare-nginx
#        networks:
#            - scribbleshare-network
#            - scribbleshare-external-network
#        build:
#            context: scribbleshare-nginx
#        depends_on:
#            scribbleshare-app:
#                condition: service_healthy
#        ports:
#            - "80:80"
# Database
    scribbleshare-postgres:
        image: stzups/scribbleshare-postgres
        networks:
            - scribbleshare-network
        build:
            context: scribbleshare-postgres
#        ports:
#            - "5432:5432"
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 5s
            timeout: 5s
            retries: 5
        environment:
            POSTGRES_PASSWORD: "changeme"
#    scribbleshare-keydb:
#        build:
#            context: scribbleshare-keydb
#        ports:
#            - "6379:6379"
#        healthcheck:
#            test: [ "CMD", "keydb-cli", "ping" ]
#            interval: 5s
#            timeout: 5s
#            retries: 5
networks:
    scribbleshare-external-network:
        driver: bridge
    scribbleshare-network:
        driver: bridge